# Generated by Django 5.1 on 2025-04-22 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(blank=True, max_length=80, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('num_holes', models.IntegerField(default=18)),
                ('course_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('resort', 'Resort'), ('semi-private', 'Semi-private')], default='public', max_length=50)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holes', to='courses.course')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('course', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Tee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('slope', models.FloatField()),
                ('total_yardage', models.IntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tees', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='HoleTee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yardage', models.IntegerField()),
                ('par', models.IntegerField()),
                ('handicap', models.IntegerField()),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hole_tees', to='courses.hole')),
                ('tee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hole_tees', to='courses.tee')),
            ],
            options={
                'unique_together': {('hole', 'tee')},
            },
        ),
    ]
