# Generated by Django 5.1 on 2025-04-23 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tee',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='tee',
            name='slope',
        ),
        migrations.CreateModel(
            name='TeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('rating', models.FloatField()),
                ('slope', models.FloatField()),
                ('tee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='courses.tee')),
            ],
            options={
                'unique_together': {('tee', 'gender')},
            },
        ),
    ]
