# Generated by Django 5.1.3 on 2025-04-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_tee_rating_remove_tee_slope_teedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='teedetails',
            name='par',
            field=models.IntegerField(null=True),
        ),
    ]
