# Generated by Django 5.1.3 on 2025-04-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_teedetails_par'),
    ]

    operations = [
        migrations.AddField(
            model_name='teedetails',
            name='back_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='teedetails',
            name='back_slope',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teedetails',
            name='bogey_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='teedetails',
            name='front_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='teedetails',
            name='front_slope',
            field=models.IntegerField(null=True),
        ),
    ]
